### ISSUE TITLE
Add an option for hiding the permission dropdown

### ISSUE THREAD

**Issue by dhermyt** [Cimpress/react-cimpress-comment#102]
It would be nice to have an option to hide this dropdown, then the `Post` button should go to the same row as comment input.

![image](https://user-images.githubusercontent.com/8223161/51105412-31183680-17e9-11e9-99f5-aad61807cad5.png)

**Comment by rnowosielski** [comment]
In case there is no drop down, I guess the component should have a prop to default it to one or the other level... ?

**Comment by dhermyt** [comment]
Exactly, I would say that the consequences of setting this prop are those visual changes.

**Comment by istanishev** [comment]
#104 #103
