### ISSUE TITLE
Adjust the component to the latest API changes

### ISSUE THREAD

**Issue by ro-tex** [Cimpress/react-cimpress-comment#11]
There were some API changes based on this issue: https://cimpress.githost.io/trdelnik/comment-service/issues/21

It would be nice to update the React component to match those.

**Comment by rnowosielski** [comment]
@ro-tex what exactly is missing ?

**Comment by ro-tex** [comment]
There doesn't seem to be any breaking changes, actually. When I created this issue in December the component didn't work with the latest version but I'm not sure why. The API changes I had in mind should not affect it at all - it's not using PUT and it doesn't seem to be POST-ing on `/resources` with a creator field in the `comment` object. So it should be fine.

**Comment by rnowosielski** [comment]
I think it is using PUT for editing existing comment.

**Comment by ro-tex** [comment]
Yes, but that's on a different endpoint. That's fine.

**Comment by rnowosielski** [comment]
ok - it is not doing that. closing!
