### ISSUE TITLE
Add "Delete Comment" button

### ISSUE THREAD

**Issue by wparad** [Cimpress/react-cimpress-comment#115]
I don't believe there is a way to delete a comment after it has been created.

**Comment by rnowosielski** [comment]
Is that something that you noticed and want to request for the future @wparad or is there some genuine need for this at the moment. We are aware that there is no delete button while the API allows you to delete the comment but we thought that wasn't an important use case to support from the start. 

Your feedback would help me prioritise it against other work.

**Comment by wparad** [comment]
We got the feedback a few times from one of our users that they would like to be able to delete a comment after adding it in our UI. Right now that isn't feasible option because we don't control the component. It makes sense as a feature request. If you want help prioritizing I'm happy to discuss it in PM.

**Comment by rnowosielski** [comment]
https://github.com/Cimpress/react-cimpress-comment/pulls

**Comment by Igrom** [comment]
Closed by #119 , as said above.
