### ISSUE TITLE
Comment text not selectable

### ISSUE THREAD

**Issue by ro-tex** [Cimpress/react-cimpress-comment#26]
After the adoption of the react-mentions package the text of each individual comment is no longer selectable. The mentions themselves are. I believe the `div` element that's used as overlay is causing that. I'm not sure if this is a huge limitation but it's definitely worse than not having it - users generally expect to be able to freely copy-paste stuff around.

Just a thought: Maybe it's possible to make the `div` transparent to mouse events?

**Comment by ro-tex** [comment]
Ok, this was so easy it's funny:
https://stackoverflow.com/questions/26094383/can-we-make-an-element-div-transparent-to-mouse-events

**Comment by rnowosielski** [comment]
This is addressed in version 0.2.3
