### ISSUE TITLE
Failure to prevent breaking on stylesheet changes (was: Styles of <CommentsDrawerLink /> are impacted by the parent element)

### ISSUE THREAD

**Issue by nikolaykhodov** [Cimpress/react-cimpress-comment#34]
`<CommentsDrawerLink />` is a wrapper around [`<Drawer/>`](https://static.ux.cimpress.io/react-components/latest/index.html#Drawer) and [`<Comments/>`](https://github.com/Cimpress/react-cimpress-comment/blob/master/src/Comments.jsx) and includes them inside the container element.

If the parent element of the container element overrides text styles, it affects `<Comments/>`s' styles.

I prepared a reduction with Cimpress default styles attached:

```
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { CommentsDrawerLink } from 'react-cimpress-comment'

class Home extends Component {
  componentDidMount () {
  }

  render () {

    return (
      <div>
        <div>App2</div>

        <h1>
          <CommentsDrawerLink
            resourceUri={window.location.href}
            accessToken=""
            newestFirst={false}
          />
        </h1>
      </div>
    )
  }
}

export default Home
```

**Comment by nikolaykhodov** [comment]
Reduction thumbnail:

![screen shot 2018-03-26 at 2 25 28 pm](https://user-images.githubusercontent.com/101510/37906209-96ee1206-3101-11e8-8135-70eb591fc544.png)

**Comment by Igrom** [comment]
The component breaks quite easily when external stylesheet changes are made.

Example from Fulfiller Configuration:
![screenshot from 2018-05-03 14-36-01](https://user-images.githubusercontent.com/10243844/39576710-5b934f7c-4edf-11e8-8443-53df792abf78.png)

**Comment by rnowosielski** [comment]
@istanishev is this closed now ?

**Comment by rnowosielski** [comment]
It is closed. I am sending release notes for it.
