### ISSUE TITLE
Expose the ability to make public or internal comments

### ISSUE THREAD

**Issue by rnowosielski** [Cimpress/react-cimpress-comment#35]
The new release of the service brought internal and public commenting as an option. Expose it in some nice way on the UI to be able to make a comment public, with the default being internal

**Comment by rnowosielski** [comment]
This involves also fixing how 403 on comment post is handled. Currently the 403 error is not shown on the UI instead it seems like the comment is being saved for ever.

**Comment by rnowosielski** [comment]
Resolved by #49

**Comment by Igrom** [comment]
One consequence of the merged changes is that the placeholder no longer lingers forever. Apart from this, figuring out what to do on 403s is now scope of a new ticket.
