### ISSUE TITLE
CSS not included into the npm package react-cimpress-comment

### ISSUE THREAD

**Issue by ro-tex** [Cimpress/react-cimpress-comment#9]
@victorcuena opened the following ticket under the service's repo, so I'm re-reporting it here:

 - The icon of the comments is not shown if the css of font-awesome is not added.
 - The Drawer doesn't look pretty if we don't include also the mex components css

To solve this issue, we can eather add this info into the readme to make the user add these css or include this files into the npm package.
In addition, we could use a svg icon instead of the font awesome one, so we won't have this dependency any more.

**Comment by rnowosielski** [comment]
This got solved with recent PR
